/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author mac
 */
public class RegistAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegistAdmin
     */
    public RegistAdmin() {
        initComponents();
    }
    
    private void hapusLayar(){
        RegistName.setText("");
        RegistEmail.setText("");
        RegistPass.setText("");
        RegistConfPass.setText("");
    }
    
    private boolean checkEmail(String RegistEmail){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkEmail = false;
        String query = "SELECT * FROM `data_login` WHERE `email` =?";
        try {
            ps = Connector.getConnection().prepareStatement(query);
            ps.setString(1,RegistEmail);
            rs = ps.executeQuery();
            if(rs.next()){
                checkEmail = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return checkEmail;
    }
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createRegAdmin = new javax.swing.JButton();
        RegistPass = new javax.swing.JPasswordField();
        RegistConfPass = new javax.swing.JPasswordField();
        RegistName = new javax.swing.JTextField();
        RegistEmail = new javax.swing.JTextField();
        cancelRegAdmin = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Admin Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Registration");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("email");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Confirm Password");

        createRegAdmin.setText("Create");
        createRegAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRegAdminActionPerformed(evt);
            }
        });

        RegistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistNameActionPerformed(evt);
            }
        });

        RegistEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistEmailActionPerformed(evt);
            }
        });

        cancelRegAdmin.setText("Cancel");
        cancelRegAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(92, 92, 92))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(118, 118, 118)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RegistPass, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(RegistName)
                                    .addComponent(RegistEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(RegistConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelRegAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createRegAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel5)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RegistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RegistEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RegistPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RegistConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRegAdmin)
                    .addComponent(cancelRegAdmin))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistNameActionPerformed

    private void RegistEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistEmailActionPerformed

    private void createRegAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRegAdminActionPerformed
        String pass = String.valueOf(RegistPass.getPassword());
        String rePass = String.valueOf(RegistConfPass.getPassword());
        
        
        if (!pass.equals(rePass)){
            JOptionPane.showMessageDialog(null, "Password is not match");
            hapusLayar();
        }else{
            PreparedStatement ps;
            String query = "INSERT INTO `data_login`(`name`, `email`, `pass`) VALUES ('"+ RegistName.getText() +"','"+ RegistEmail.getText() + "','" + pass +"')";
        
            try {
                ps = Connector.getConnection().prepareStatement(query);
                    if (ps.executeUpdate()>0){
                        JOptionPane.showMessageDialog(null, "Register Success");
                        hapusLayar();
                    }
            }catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(null,"Email telah digunakan!", "Warning", JOptionPane.WARNING_MESSAGE);


            } catch (SQLException ex) {
                Logger.getLogger(RegistAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
        
        
        

    }//GEN-LAST:event_createRegAdminActionPerformed

    private void cancelRegAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegAdminActionPerformed
        Admin adm = new Admin();
        adm.setVisible(true);
        adm.pack();
        adm.setLocationRelativeTo(null);
        adm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cancelRegAdminActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField RegistConfPass;
    private javax.swing.JTextField RegistEmail;
    private javax.swing.JTextField RegistName;
    private javax.swing.JPasswordField RegistPass;
    private javax.swing.JButton cancelRegAdmin;
    private javax.swing.JButton createRegAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
